language: node_js
node_js: 
  - "stable"
before_script:
  - npm install -g gulp-cli

jobs:
  - stage: "Code Quality"
    script: npm run-script lint

  - stage: "test"
    script: gulp test

  - stage: "Code coverage" 

  - stage: "Deploy"