language: node_js
node_js: 
  - "stable"
before_script:
  - npm install -g gulp-cli

stages:
  - lint
  - test
  - deploy

jobs:
  include:
  - stage: lint
    script: npm run-script lint

  - stage: test
    script: gulp test

  - stage: build
    script: gulp build

  - stage: deploy
