language: node_js
node_js: 
  - "stable"

services:
  - docker
  
before_script:
  - npm install -g gulp-cli

stages:
  - lint
  - test
  - build
  - deploy

jobs:
  include:
  - stage: lint
    script: npm run-script lint

  - stage: test
    script: gulp test

  - stage: deploy
    script: bash publish_image.sh