version: "2"
services:
  transactions-gui:
    container_name: transactions-gui
    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - transactions
    volumes:
      - .:/usr/src/app/
  transactions:
    container_name: transactions-back-office
    image: jugirard/transactions-backoffice-nodejs:0.1
    ports:
      - "8080:8080"
    links:
      - mongo 
    env_file: ../Transactions/.env
  mongo:
    container_name: mongo-db
    image: mongo
    volumes:
      - ../Transactions/data:/data/db
    ports:
      - "27017:27017"